"""add_coordinates

Revision ID: f27bf5fa00ed
Revises: 
Create Date: 2026-03-06 18:50:23.120073
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f27bf5fa00ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
